2022-08-20 16:32:06,966 THis is my time stamp
2022-08-20 16:33:04,056 THis is my time stamp
2022-08-20 16:36:58,307 THis is my time stamp
2022-08-20 16:37:45,878 THis is my time stamp
2022-08-20 16:39:38,727 root THis is my time stamp
2022-08-20 16:47:13,641 root THis is my time stamp
2022-08-20 16:48:22,180 root INFO THis is my time stamp
INFO 2022-08-20 17:12:00,835 
INFO 2022-08-20 17:13:39,472 
INFO 2022-08-20 17:13:39,473 
INFO 2022-08-20 17:14:16,851 
INFO 2022-08-20 17:14:16,851 
INFO 2022-08-20 17:14:34,082 
INFO 2022-08-20 17:14:43,557 
INFO 2022-08-20 17:15:04,737 
INFO 2022-08-20 17:15:04,737 
INFO 2022-08-20 17:16:16,098 
INFO 2022-08-20 17:16:41,116 
INFO root 2022-08-20 17:18:14,899 
INFO root 2022-08-20 17:19:22,791 
INFO root 2022-08-20 17:19:22,792 
INFO root 2022-08-20 17:41:22,808 
INFO root 2022-08-20 17:41:30,133 
INFO root 2022-08-20 17:44:07,253 the number entred by the user is 3 and 6
INFO root 2022-08-20 17:45:07,697 the number entred by the user is 3 and 6
INFO root 2022-08-20 17:45:07,698 Result=0.5
INFO root 2022-08-20 17:45:26,260 the number entred by the user is 3 and 6
INFO root 2022-08-20 17:45:26,260 Result=0.5
INFO root 2022-08-20 17:45:45,512 the number entred by the user is 3 and 6
INFO root 2022-08-20 17:45:51,191 the number entred by the user is 3 and 6
INFO root 2022-08-20 17:45:51,191 Result=0.5
INFO root 2022-08-20 17:52:03,523 the number entred by the user is 3 and 6
INFO root 2022-08-20 17:52:03,523 we are in function
INFO root 2022-08-20 17:52:03,523 we have completed division operation
INFO root 2022-08-20 17:52:03,523 Result=0.5
INFO root 2022-08-20 17:52:52,280 the number entred by the user is 3 and 0
INFO root 2022-08-20 17:52:52,280 we are in function
ERROR root 2022-08-20 17:52:52,280 division by zero
Traceback (most recent call last):
  File "c:\Users\adity\Desktop\ineuron\test.py", line 11, in devide
    dev=a/b
ZeroDivisionError: division by zero
INFO root 2022-08-20 17:52:52,281 Result=None
INFO root 2022-09-04 18:05:14,189 the number entred by the user is 3 and 0
INFO root 2022-09-04 18:05:14,189 we are in function
ERROR root 2022-09-04 18:05:14,189 division by zero
Traceback (most recent call last):
  File "c:\Users\adity\Desktop\python\test.py", line 11, in devide
    dev=a/b
ZeroDivisionError: division by zero
INFO root 2022-09-04 18:05:14,189 Result=None
INFO root 2022-09-04 18:05:29,945 the number entred by the user is 3 and 0
INFO root 2022-09-04 18:05:29,945 we are in function
ERROR root 2022-09-04 18:05:29,945 division by zero
Traceback (most recent call last):
  File "c:\Users\adity\Desktop\python\test.py", line 11, in devide
    dev=a/b
ZeroDivisionError: division by zero
INFO root 2022-09-04 18:05:29,945 Result=None
INFO root 2022-09-06 19:14:29,040 the number entred by the user is 3 and 0
INFO root 2022-09-06 19:14:29,044 we are in function
ERROR root 2022-09-06 19:14:29,044 division by zero
Traceback (most recent call last):
  File "c:\Users\adity\Desktop\python\test.py", line 11, in devide
    dev=a/b
ZeroDivisionError: division by zero
INFO root 2022-09-06 19:14:29,044 Result=None
